In [70]:
def when_offered(courses, course):
    season=[]
    for sem,subject in courses.items():
        for course_code,details in subject.items():
            
            if course_code == course:
                season.append(sem)
    return season

In [71]:
courses = {
    'spring2020': { 'cs101': {'name': 'Building a Search Engine',
                           'teacher': 'Dave',
                           'assistant': 'Peter C.'},
                 'cs373': {'name': 'Programming a Robotic Car',
                           'teacher': 'Sebastian',
                           'assistant': 'Andy'}},
    'fall2020': { 'cs101': {'name': 'Building a Search Engine',
                           'teacher': 'Dave',
                           'assistant': 'Sarah'},
                 'cs212': {'name': 'The Design of Computer Programs',
                           'teacher': 'Peter N.',
                           'assistant': 'Andy',
                           'prereq': 'cs101'},
                 'cs253': {'name': 'Web Application Engineering - Building a Blog',
                           'teacher': 'Steve',
                           'prereq': 'cs101'},
                 'cs262': {'name': 'Programming Languages - Building a Web Browser',
                           'teacher': 'Wes',
                           'assistant': 'Peter C.',
                           'prereq': 'cs101'},
                 'cs373': {'name': 'Programming a Robotic Car',
                           'teacher': 'Sebastian'},
                 'cs387': {'name': 'Applied Cryptography',
                           'teacher': 'Dave'}},
    'spring2044': { 'cs001': {'name': 'Building a Quantum Holodeck',
                           'teacher': 'Dorina'},
                        'cs003': {'name': 'Programming a Robotic Robotics Teacher',
                           'teacher': 'Jasper'},
                     }
    }


when_offered(courses,'bio893')

[]

In [75]:
# Definition of the generator to produce even numbers.
def all_even():
    n = 0
    while True:
        yield n
        n += 2

my_gen = all_even()

# Generate the first 5 even numbers.
for i in range(5):
    print(next(my_gen))

# Now go and do some other processing.
do_something = 4
do_something += 3
print('llll',do_something)

# Now go back to generating more even numbers.
for i in range(100):
    print(next(my_gen))

0
2
4
6
8
llll 7
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100
102
104
106
108
110
112
114
116
118
120
122
124
126
128
130
132
134
136
138
140
142
144
146
148
150
152
154
156
158
160
162
164
166
168
170
172
174
176
178
180
182
184
186
188
190
192
194
196
198
200
202
204
206
208

In [79]:
def prod(a,b):
    # TODO change output to the product of a and b
    output = a*b
    return output

def fact_gen():
    i = 1
    n = i
    while True:
        output = prod(n, i)
        yield output
        n=output
        i+=1
        # TODO: update i and n
        # Hint: i is a successive integer and n is the previous product
        
# Test block
my_gen = fact_gen()
num = 5
for i in range(num):
    print(next(my_gen))

1
2
6
24
120

In [119]:
c = [[1,2,3],
           [2,3,1],
           [3,1,2]]
row=[]
column=[]

def sudoko(correct):
        bool=None
        for i in range(0,len(correct)):
                row.clear()
                column.clear()
                for j in range(0,len(correct)):
                        if bool is True or bool is None :
                                if correct[i][j] not in row and correct[j][i] not in column  :
                                        row.append(correct[i][j])
                                        column.append(correct[i][j])
                                        bool = True
                                else:
                                        bool=False
                                
                                
        return bool
                
                        

print(sudoko(c))

True

In [173]:
square = [[1,2,3],
           [2,3,1],
           [3,1,2]]

def sudoko(square):
    for row in square:
        check_list=list(range(1,(len(square[0])+1)))
        for value in row:
             if value not in check_list:
                 return False
             
             check_list.remove(value)
             
             
    for n in range(len(square)):
        
        check_list=list(range(1,(len(square[0])+1)))
        
        for row in square:
            
            if row[n] not in check_list:
                return False


            
            check_list.remove(row[n])

           
           
    return True
               
        
        
sudoko(square)

True

In [178]:
class Person:
    def __init__(self, name, age):
        self.person_name = name
        self.person_age = age

    def birthday(self):
        self.person_age += 1

    def getName(self):
        return self.person_name
    
b1=Person('aravind',27)

b1.person_name

'aravind'

In [203]:
class Person:
    def __init__(self, name, age, month):
        self.name = name
        self.age = age
        self.birthday_month = month
        
    def birthday(self):
        self.age += 1

def create_person_objects(names, ages, months):
    my_data = zip(names, ages, months)
    person_objects = []
    for item in my_data:
        person_objects.append(Person(*item))
    return person_objects

def get_april_birthdays(people):
    april_birthdays = {}
    for obj in people:
        if obj.birthday_month=='April':
            current_year_age=obj.age +1
            april_birthdays[obj.name]=current_year_age 
    return april_birthdays
            

def get_most_common_month(people):
    most_bd_month={}
    max_value=0
    max_month=None
    for obj in people:
        if obj.birthday_month not in most_bd_month.keys():  
            most_bd_month[obj.birthday_month]=1
        else:
            most_bd_month[obj.birthday_month]+=1
        for key in most_bd_month.keys():
            if most_bd_month[key] > max_value:
                max_value = most_bd_month[key]
                max_month=key
    return max_month

        
  

def test():
    # Here is the data for the test. Assume there is a single most common month.
    names = ['Howard', 'Richard', 'Jules', 'Trula', 'Michael', 'Elizabeth', 'Richard', 'Shirley', 'Mark', 'Brianna', 'Kenneth', 'Gwen', 'William', 'Rosa', 'Denver', 'Shelly', 'Sammy', 'Maryann', 'Kathleen', 'Andrew', 'Joseph', 'Kathleen', 'Lisa', 'Viola', 'George', 'Bonnie', 'Robert', 'William', 'Sabrina', 'John', 'Robert', 'Gil', 'Calvin', 'Robert', 'Dusty', 'Dario', 'Joeann', 'Terry', 'Alan', 'Rosa', 'Jeane', 'James', 'Rachel', 'Tu', 'Chelsea', 'Andrea', 'Ernest', 'Erica', 'Priscilla', 'Carol', 'Michael', 'Dale', 'Arthur', 'Helen', 'James', 'Donna', 'Patricia', 'Betty', 'Patricia', 'Mollie', 'Nicole', 'Ernest', 'Wendy', 'Graciela', 'Teresa', 'Nicole', 'Trang', 'Caleb', 'Robert', 'Paul', 'Nieves', 'Arleen', 'Milton', 'James', 'Lawrence', 'Edward', 'Susan', 'Patricia', 'Tana', 'Jessica', 'Suzanne', 'Darren', 'Arthur', 'Holly', 'Mary', 'Randal', 'John', 'Laura', 'Betty', 'Chelsea', 'Margaret', 'Angel', 'Jeffrey', 'Mary', 'Donald', 'David', 'Roger', 'Evan', 'Danny', 'William']
    ages  = [17, 58, 79, 8, 10, 57, 4, 98, 19, 47, 81, 68, 48, 13, 39, 21, 98, 51, 49, 12, 24, 78, 36, 59, 3, 87, 94, 85, 43, 69, 15, 52, 57, 36, 52, 5, 52, 5, 33, 10, 71, 28, 70, 9, 25, 28, 76, 71, 22, 35, 35, 100, 9, 95, 69, 52, 66, 91, 39, 84, 65, 29, 20, 98, 30, 83, 30, 15, 88, 89, 24, 98, 62, 94, 86, 63, 34, 23, 23, 19, 10, 80, 88, 67, 17, 91, 85, 97, 29, 7, 34, 38, 92, 29, 14, 52, 94, 62, 70, 22]
    months = ['January', 'March', 'January', 'October', 'April', 'February', 'August', 'January', 'June', 'August', 'February', 'May', 'March', 'June', 'February', 'August', 'June', 'March', 'August', 'April', 'April', 'June', 'April', 'June', 'February', 'September', 'March', 'July', 'September', 'December', 'June', 'June', 'August', 'November', 'April', 'November', 'August', 'June', 'January', 'August', 'May', 'March', 'March', 'March', 'May', 'September', 'August', 'April', 'February', 'April', 'May', 'March', 'March', 'January', 'August', 'October', 'February', 'November', 'August', 'June', 'September', 'September', 'January', 'September', 'July', 'July', 'December', 'June', 'April', 'February', 'August', 'September', 'August', 'February', 'April', 'July', 'May', 'November', 'December', 'February', 'August', 'August', 'September', 'December', 'February', 'March', 'June', 'December', 'February', 'May', 'April', 'July', 'March', 'June', 'December', 'March', 'July', 'May', 'September', 'November']
    people = create_person_objects(names, ages, months)

    # Calls to the two functions you have completed.
    #print(get_april_birthdays(people))
    print(get_most_common_month(people))



test()

August

In [ ]:
def nextDay(year, month, day):
    
    
    if day <30:
        return (year , month ,day+1)
    
    else:
        if month ==12:
            return (year+1,1,1)
        else:
            return (year,month+1,1)
        
        
def daysBetweenDates(year1, month1, day1, year2, month2, day2):
    
    """Returns the number of days between year1/month1/day1
       and year2/month2/day2. Assumes inputs are valid dates
       in Gregorian calendar, and the first date is not after
       the second."""
       
    diffyr=year2-year1
    day_diff=day2-day1
    month_diff=month2-month1
    if  diffyr == 0:  
        if (month1 <= month2) and (day1 <=  day2) and (day1 > 0):
            print('validated')
            totaldays=day_diff + month_diff*30  
            return totaldays
        elif (month1 >= month2) and (day1 > day2) or (day1 < 0):
            print('give proper day1 and day2')   
                       
    elif diffyr <0:
        print('give greater year')
        
    else:
        print('hi')
        totaldays=diffyr*360 +month_diff *30 + day_diff    
        return totaldays
      
        
#nextDay(2025,12,30)
#daysBetweenDates(2012,9,30,2012,10,30)
def test():
    test_cases = [((2012,9,30,2012,10,30),30), 
                  ((2012,1,1,2013,1,1),360),
                  ((2012,9,1,2012,9,4),3)]
    
    for (args, answer) in test_cases:
        result = daysBetweenDates(*args)
        if result != answer:
            print ("Test with data:", args, "failed")
        else:
            print ("Test case passed!")

test()

In [357]:
def is_leapyr(year):
    if ((year % 4==0) and (year % 100 !=0)) or (year % 400 ==0):
        return  True

    else:
        return False

def daysinmonth(year,month):

    days=0
    if month in [1,3,5,7,8,10,12]:
        days+=31
    elif month == 2: 
        if is_leapyr(year):
            days+=29
        else:
            days += 28    
    else:
        days +=30
    return days

def nextDay(year, month, day):
    month_days=daysinmonth(year,month)
    
    if day <month_days:
        return (year , month ,day+1)
    
    else:
        if month ==12:
            return (year+1,1,1)
        else:
            return (year,month+1,1)

        
def Dateisbefore(year1, month1, day1, year2, month2, day2):
    if year1 < year2:
        return True
    if year1==year2:
        if month1<month2:
            return True  
        if month1==month2 :
            return day1<day2
    return False
    
def daysbetweendates(year1, month1, day1, year2, month2, day2):
    assert not Dateisbefore(year2, month2, day2,year1, month1, day1)
    days=0
    while Dateisbefore(year1, month1, day1, year2, month2, day2):
        year1, month1, day1= nextDay(year1, month1, day1)
        days+=1
    return days



def test():
    test_cases = [((2012,1,1,2012,2,28), 58), 
                  ((2012,1,1,2012,3,1), 60),
                  ((2011,6,30,2012,6,30), 366),
                  ((2011,1,1,2012,8,8), 585 ),
                  ((1900,1,1,1999,12,31), 36523)]
    
    for (args, answer) in test_cases:
        result = daysbetweendates(*args)
        if result != answer:
            print("Test with data:", args, "failed")
        else:
            print ("Test case passed!")
            
            
#test()
#daysbetweendates(2012,1,1,2012,2,28)
def test_case():
    assert daysbetweendates(2012,2,1,2012,2,28)== 27
print ("test_completed")


test_case()        
    
#daysinmonth(2024,2)

#is_leapyr(1904)

test_completed

In [23]:
scores = {'Alice': 82, 'Bob': 91, 'Charlie': 78}

def find_max_dict(scores):
    max_value=0
    d={}      
    for key ,values in scores.items():
    
        if values > max_value:
            max_value=values
            d.clear()
            d[key]=values
          
    return d

print(max(scores,key=scores.get))

Bob

In [32]:
d={1,2,3,1}

print(d.pop())
print(d.remove(3))
print(d)

1
None
{2}

In [89]:
# server.py
from flask import Flask, request, jsonify
app = Flask(__name__)

@app.route("/login", methods=["POST"])
def login():
    data = request.json
    if data["username"] == "admin":
        return jsonify({"msg": "Welcome!"}), 200
    return jsonify({"msg": "Invalid"}), 403

if __name__ == "__main__":
    app.run(port=8000)

ModuleNotFoundError: No module named 'flask'

In [86]:
c=school('aravind','100')
print(c)

aravind